name: Change_containerPort_nodePort
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - Prod
      portType:
        description: 'Which port to update? (containerPort or nodePort)'
        required: true
        type: choice
        options:
          - containerPort
          - nodePort
      portValue:
        description: 'New port value'
        required: true
        default: '30009'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       ENVIRONMENT: ${{ github.event.inputs.environment }}
       PORT_TYPE: ${{ github.event.inputs.portType }}
       PORT_VALUE: ${{ github.event.inputs.portValue }}
    steps:
    ## Clone ArgoCD example repo
      - name: Clone ArgoCD example repo
        env:
           TOKEN : ${{ secrets.TOKEN  }}

        run: |
           git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/satishnaga1/argocd-example-apps.git

  # Change ContainerPort in deployment manifest
      - name: Update port based on selection
        run: |
          if [ "$PORT_TYPE" = "containerPort" ]; then
            echo "Updating containerPort to $PORT_VALUE"
            sed -i "s/containerPort: [0-9]\+/containerPort: $PORT_VALUE/" argocd-example-apps/$ENVIRONMENT/deploy.yaml
          elif [ "$PORT_TYPE" = "nodePort" ]; then
            echo "Updating nodePort to $PORT_VALUE"
            sed -i "s/nodePort: [0-9]\+/nodePort: $PORT_VALUE/" argocd-example-apps/$ENVIRONMENT/svc.yaml
          else
            echo "Invalid port"
            exit 1
          fi

      # Commit and push updated manifest
      - name: Commit and push deployment update
        run: |
          cd argocd-example-apps
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/satishnaga1/argocd-example-apps.git
          if [ "$PORT_TYPE" = "containerPort" ]; then
            git add $ENVIRONMENT/deploy.yaml
            git commit -m "Update containerPort to $PORT_VALUE in $ENVIRONMENT"
          else
            git add $ENVIRONMENT/svc.yaml
            git commit -m "Update nodePort to $PORT_VALUE in $ENVIRONMENT"
          fi
          git push

        env:
          TOKEN: ${{ secrets.TOKEN }}
